"""automatic migration

Revision ID: 0434b3ffc095
Revises: 180388858785
Create Date: 2023-11-15 13:16:30.253795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0434b3ffc095'
down_revision = '180388858785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_member', schema=None) as batch_op:
        batch_op.alter_column('meet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('meet', schema=None) as batch_op:
        batch_op.alter_column('troop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('troop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.alter_column('member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('meet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.alter_column('member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('troop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.alter_column('troop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('member_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.alter_column('meet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('member_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('troop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('meet', schema=None) as batch_op:
        batch_op.alter_column('troop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('check_member', schema=None) as batch_op:
        batch_op.alter_column('meet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
