"""automatic migration

Revision ID: 462eeae40978
Revises: 4545cd806ac5
Create Date: 2023-11-22 20:32:31.126107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462eeae40978'
down_revision = '4545cd806ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_member', schema=None) as batch_op:
        batch_op.drop_column('sent')

    # ### end Alembic commands ###
