"""Add tables and relaitons ships

Revision ID: 499cbad39f75
Revises: d0f372d0ebaa
Create Date: 2023-10-28 16:38:12.303679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499cbad39f75'
down_revision = 'd0f372d0ebaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('photograpy_url', sa.String(length=240), nullable=True),
    sa.Column('troop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['troop_id'], ['troop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('mobile', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=240), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('member_name', sa.String(length=120), nullable=False),
    sa.Column('other_desc', sa.String(length=300), nullable=False),
    sa.Column('confirm', sa.Boolean(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('meet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meet_id'], ['meet.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('meet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meet_id'], ['meet.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('troop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['troop_id'], ['troop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('register')
    op.drop_table('points')
    op.drop_table('check_member')
    op.drop_table('member')
    op.drop_table('meet')
    # ### end Alembic commands ###
